package com.mayank.SpringMongoDB;

import com.mayank.SpringMongoDB.dto.CustomerDTO;
import com.mayank.SpringMongoDB.idgenerator.GenerateId;
import com.mayank.SpringMongoDB.service.CustomerService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class SpringMongoDbApplication
{

	public static void main(String[] args)
	{
		ConfigurableApplicationContext container = SpringApplication.run(SpringMongoDbApplication.class, args);
		CustomerService service = container.getBean(CustomerService.class);

		CustomerDTO dto = new CustomerDTO("Roma", "USA", 35);

		//generating random id using UUID and adding to DTO
		//by using this we have just replaced the unique  id generated by mongodb
		//for every document by our own custom id.
		dto.setId(GenerateId.get());

		String mssg = service.registerCustomer(dto);
		System.out.println(mssg);

		String result = service.findById("678b9b5a6760365f32229e8");
		System.out.println(result);
	}

}
